Repository discovery-tecnologia/dsc-mercado-livre, pull requests merged in 2021-03, with the labels that each got.

#71 Atualização do Category-Predictor
  src/Requests/Category/CategoryService.php
  src/Requests/Category/Predictor.php
  tests/Requests/Category/PredictorTest.php
  tests/Requests/Category/fixtures/predictor.json
Labels: bug, enhancement

#75 Suporte ao multi tenant session
  src/AccessToken.php
  src/Handler/OAuth2ClientHandler.php
  src/Resources/Authorization/AuthorizationService.php
  tests/AccessTokenTest.php
Labels: bug

#77 Adicionado opcao para setar o user-id na classe Meli
  src/AccessToken.php
  src/Handler/OAuth2ClientHandler.php
  src/Meli.php
  src/MeliInterface.php
  src/Resources/Authorization/AuthorizationService.php
  tests/AccessTokenTest.php
  tests/MeliTest.php
Labels: enhancement

#78 feat(authorizationService) add param state to getOauthUrl method
  README.md
  src/Resources/Authorization/AuthorizationService.php
Labels: bug
